### ISSUE TITLE
Adapt new schema validator messages to the existing ProcessingMessage format

### ISSUE THREAD

**Issue by asoltysik** [snowplow/iglu-scala-client#109]

**Comment by alexanderdean** [comment]
Can you clarify what this ticket does? Does it adapt the ProcessingMessage, or does it populate the existing ProcessingMessage from a different source? That makes a huge difference.

/cc @chuwy

**Comment by asoltysik** [comment]
Hopefully the wording is now clearer @alexanderdean

**Comment by alexanderdean** [comment]
Thanks, please update the commit!
