### ISSUE TITLE
Drop failures from cache after period of time

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#110]
Current caching algorithm saves failed responses that [can be recovered](https://github.com/snowplow/iglu-scala-client/blob/master/src/main/scala/com.snowplowanalytics.iglu/client/Resolver.scala#L225-L231), but retries them only several times. If after 3 times registry still responds with error - resolver stops retrying it.

This algorithm doesn't have a notion of time: if it was 3 subsequent errors in 1 second - it will never retry anymore (unless `cacheTtl` has expired). This is undesired in streaming environment, where we have very big chance that registry has recovered (streaming job can be running for several weeks). Hence resolver needs to keep retrying.

I think we should have an option in resolver.json when to reset information about failures (e.g. `cacheFailureTtl`). This will allow us to make `cacheTtl` much higher and at the same time have significantly less chance to drop good data because of registry issues.

**Comment by alexanderdean** [comment]
Good catch!

**Comment by szareiangm** [comment]
we were dealing with this issue today. :(

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/iglu-scala-client/issues/77
