### ISSUE TITLE
Replace HttpRepositoryRef's fetch code with spray-can

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-scala-client#13]

**Comment by chuwy** [comment]
This is not actually blocking https://github.com/snowplow/iglu-scala-client/issues/12, I implemented it with stdlib. Also I don't know whether smth like spray-can or akka-http would be good for this kind of work, but yes we need more flexible HTTP client.

**Comment by alexanderdean** [comment]
Good to know, thanks @chuwy

**Comment by chuwy** [comment]
Not relevant anymore
