### ISSUE TITLE
Consider switching from Map to SortedMap in 1.0.0

### ISSUE THREAD

**Issue by dilyand** [snowplow/iglu-scala-client#130]
The `MapCoder` used in Scio / Beam is considered to be non-deterministic, so any AST containing a `Map` somewhere in its hierarchy cannot be used as a key in `groupByKey` operations (because the higher-level derived `Coder` will also be  non-deterministic).

This is an issue, for example, in https://github.com/snowplow-product/gcp-bad-row-aggregator where we want to be able to group by error but can't since `ClientError` can have a `Map` as one of its fields: 

```
object ClientError {

  /** Error happened during schema resolution step */
  final case class ResolutionError(value: Map[String, LookupHistory]) extends ClientError {
    def isNotFound: Boolean =
      value.values.flatMap(_.errors).forall(_ == RegistryError.NotFound)
  }

???
}
```

Changing this to `SortedMap[String, LookupHistory]` fixes the downstream issue. The change is demonstrated here: https://github.com/snowplow/iglu-scala-client/pull/129

**Comment by istreeter** [comment]
Closing this, because I think it was implemented in #147
