### ISSUE TITLE
Add Scala 2.11 support

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-scala-client#29]
Blocking https://github.com/snowplow/schema-guru/issues/47

**Comment by chuwy** [comment]
Hey @ninjabear. In case you still need it - 2.11 support got merged.

**Comment by ninjabear** [comment]
thanks @chuwy !

**Comment by chuwy** [comment]
@ninjabear one little remark: you'll probably need to switch to scalaz-7.0.8 as it cross-compiled for 2.10 and 2.11.
