### ISSUE TITLE
Add schema lookup retry n times in case of non-404 error

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-scala-client#38]
This is a follow-on from #30. The problem is that if we are very unlucky and the first attempt to fetch a schema is a miss due to a network glitch, then this schema is cached as missing for the rest of the job run.

We had this with a customer where a single Hadoop worker failed a schema lookup and all subsequent JSON instances processed by that worker failed validation due to the schema being cached as missing.

The proposed solution is to require 3 failures before caching a schema as missing.

**Comment by fblundun** [comment]
There are 2 possible parts to this:

* attempting up to m retries when retrieving the schema for a single event
* waiting until we have failed to get the schema for n separate events to give up on getting the schema at all for subsequent events

**Comment by alexanderdean** [comment]
Thanks for splitting this out Fred. My gut feel is that we do both. A question I have is whether we do m retries on all repos, or only on repos which are associated with the vendor prefix (i.e. we use the vendor prefix as a hint that com.acme.foo _really_ ought to be in _this_ repo, so try again)...

**Comment by alexanderdean** [comment]
I just had another thought - which is that if an Iglu Scala repo server could give a very definitive response ("this schema is **not** in this repo"), then the risk of confusion between "network I/O issue, try again?" and "this schema is not in this repo" would go away...

**Comment by fblundun** [comment]
That's true. Even for the static repo it should be possible to tell the difference between a 404 Not Found and other connectivity problems...

**Comment by alexanderdean** [comment]
Sounds good - I think then we can do both. Split this ticket into two?

**Comment by alexanderdean** [comment]
Renamed ticket to make it MECE with #44
