### ISSUE TITLE
If schema lookup returns a 404, immediately cache the fact it is missing

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu-scala-client#44]

**Comment by fblundun** [comment]
See #38

**Comment by chuwy** [comment]
This is fixed by https://github.com/snowplow/iglu-scala-client/commit/1ad73cbac30413fc75ca6f4e88ad7e9906e7fa56.

**Comment by alexanderdean** [comment]
Descheduling and closing as covered by #38
