### ISSUE TITLE
Add configurable cache max-age for schemas

### ISSUE THREAD

**Issue by jbeemster** [snowplow/iglu-scala-client#56]
In the case of Stream Enrich if an event is sent multiple times without the relevant schema being available the schema is then locked into a "bad cache".  Subsequent requests with this schema are then automatically invalidated - even if in the meantime the schema is added and is now available.

The only way to resolve the above is to manually reboot all Stream Enrich instances so that the cache is reset - but this also involves losing all of the "good" schemas they have cached.

With a max-age argument this could be resolved automatically without human intervention.

**Comment by alexanderdean** [comment]
When this has been done and all the way through to Stream Enrich, we should update the guide here: http://discourse.snowplowanalytics.com/t/understanding-schema-validation-and-caching-in-snowplow/225

**Comment by alexanderdean** [comment]
Default if not set should be max age infinity - i.e. same as current behavior
