### ISSUE TITLE
Fix handling of incorrect $schema key

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#57]
I saw many times people used non-existent HTTP URIs (usually they try to point it to their own newly created Schema) as content for `$schema` key and that didn't cause any problems.

But it turns out `com.github.fge.json-schema-validator` throws an exception if it see invalid URI (in our case it was `iglu:` protocol) and that exception is very well hidden in EMR logs, while shredded/bad is empty.

Seems like a companion for #47

**Comment by alexanderdean** [comment]
Great spot - scheduling!

**Comment by alexanderdean** [comment]
Can you also create tickets for snowplow/snowplow?

**Comment by chuwy** [comment]
Thanks to @ihortom

**Comment by chuwy** [comment]
Yes, sure.

**Comment by alexanderdean** [comment]
Are we working on 0.4.1 or 0.5.0? Update milestones please @chuwy

**Comment by chuwy** [comment]
Sorry, we're working on 0.5.0. Updating!
