### ISSUE TITLE
Add support for Scala 2.12

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#66]
Json4s was holding us back from 2.12 support, because EOL version is embedded into Spark, but recently 3.2.11 was [backported to 2.12](https://github.com/json4s/json4s/commit/8c2865089604677578e3d858056014b12d2a78dc), which means we can safely bump version.

Scalaz 7.0.9 also supported by 2.12, but I think we need to come up with deprecation plan of it.

This is quite important for our eco-system because Iglu Client is deepest dependency in most of our libs and apps.

**Comment by alexanderdean** [comment]
Create a separate ticket for the Scalaz deprecation...

**Comment by szareiangm** [comment]
Can we do it as we deprecate 2.10? 
It is hard to find libraries that behave the same for 2.10, 2.11, and 2.12. Moreover, Spec2 doesn't have a version for three of them
https://mvnrepository.com/artifact/org.specs2/specs2
@chuwy  @alexanderdean

**Comment by chuwy** [comment]
@szareiangm yes, I'm totally fine with deprecating 2.10. 2.11 and 2.12 are most common versions.
