### ISSUE TITLE
Loosen a schema criterion for Resolver config

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#68]
Currently Resolver configuration restricts config to `iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-2` and Scala Client's implementation of criterion makes it match all versions lower on addition, but not higher.

It means that applications with Iglu Client 0.4.0 cannot parse config of `1-0-2` (was added in 0.5.0).

**Comment by alexanderdean** [comment]
Ouch!

**Comment by chuwy** [comment]
Need to be done with #20.

**Comment by chuwy** [comment]
This was implemented as part of #20
