### ISSUE TITLE
Fix URL-concatenation in HttpRepositoryRef

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#69]
[This](https://github.com/snowplow/iglu-scala-client/blob/master/src/main/scala/com.snowplowanalytics.iglu/client/repositories/HttpRepositoryRef.scala#L201) should not blindly concatenate provided URL and `/schemas/`. Also we can add preliminary validation of `uri` as not all URIs can be correct endpoint.

**Comment by alexanderdean** [comment]
What should the behavior be instead?

**Comment by chuwy** [comment]
We have few options:

1. Force absence of trailing `/` in resolver-config schema
2. Failing with meaningful error message if trailing slash is there
3. Removing trailing slash if it is present: `if url.enswith('/'): url.rstrip('/') else url`

I'd like to go with third option.

**Comment by alexanderdean** [comment]
Sounds good

**Comment by saj1th** [comment]
@chuwy  - Is removing the trailing slash for url at HttpRepositoryRef.scala the only change ?

**Comment by chuwy** [comment]
@saj1th actual logic should also check if trailing slash is already present. If not - add it. Otherwise - yes.

**Comment by saj1th** [comment]
@chuwy 

did you mean if already present remove, and not present - do nothing.
More like 

    val urlNorm =
      if (url.endsWith("/")) url.substring(0, url.length - 1) else url

Looks like a trivial change - but happy to help :)

**Comment by chuwy** [comment]
That's right. Trivial change, significant UX improvement.

I'd just change `url.substring(0, url.length - 1)` to `url.dropRight(1)` as we don't want to mess with indexes too much.

**Comment by saj1th** [comment]
👍

**Comment by chuwy** [comment]
This was incorporated into #113
