### ISSUE TITLE
Stop invalidating cache on registry failures

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-scala-client#77]
Currently if we re-fetch schema due expired TTL and registry fails to respond (e.g. code 5xx, while 4xx is **not** considered as failure), this failure will be added to cache and stored until next expired TTL invalidating all encountered instances.

I think failures should never override successful responses in cache, because in real-time pipeline each such failure results in big amount of bad rows that don't have semantic meaning. 4xx responds mean something semantically ("schema is not there"), while 5xx are always infrastructure/registry outage. 

So, the only chance for failure to appear in cache should be due first request (or overriding another failure).

**Comment by alexanderdean** [comment]
Good point.

**Comment by chuwy** [comment]
Prioritizing

**Comment by chuwy** [comment]
This feature changes the logic of Resolver quite significantly:

1. First, we now refuse to overwrite successful responses with failures.  Only LRU policy can evict failed response. In other words - retain successful value as long as possible.
2. We removed `attempt` argument from `lookupSchema` function. It doesn't make sense to have fixed amount of attempts in a streaming environment.
3. Instead, we rely on `cacheTtl` and backoff policy. Backoff policty uses `lastAttempt` (available also in `LookupHistory`, which is a part of Iglu Client error JSON) to decide when resolver can re-fetch the schema again. Miniimum backoff is ~500ms, maximum 20mins.


High-level consequences:

1. Iglu Resolver now is more streaming-oriented
2. Chance of accidentally fetching an error response and invlidate data is extremely small
3. There's an assumption that cache can hold all schemas streaming application is using (even for hundreds of schemas it will unlikely take more than 1Mb of RAM)

**Comment by alexanderdean** [comment]
This seems super wise.
