### ISSUE TITLE
Bump jackson-databind to a newer version or shade

### ISSUE THREAD

**Issue by knservis** [snowplow/iglu-scala-client#80]
This is a discussion issue. 

This project is currently using the `2.2.3` version of jackson-databind. That is a very old version (about 5 years as of now) and can be a problem for a number of reasons:
* It is likely that will get evicted by other dependencies of the user of the iglu-scala-client with unexpected results (I recently saw that happening in SCE). 
* It is likely that there have been performance and possibly also security improvements. 

I tested this library with the `2.9.5` version and the only visible consequence seemed to be the improvement of the error deserialisation. 

If for some reason we need to stick to that version we should consider shading. We may wan't to shade anyway (or provide an additional artefact that has this shaded, depending on how many use this library)

**Comment by chuwy** [comment]
Related https://github.com/snowplow/iglu-scala-client/issues/78

**Comment by istreeter** [comment]
Closing this, as it was bumped to 2.10.3 for the 1.0.2 release of iglu-scala-client (#143) and it will be bumped again in the forthcoming 1.1.0 release (#154)
