### ISSUE TITLE
Bump json4s to 3.5.4

### ISSUE THREAD

**Issue by szareiangm** [snowplow/iglu-scala-client#90]

**Comment by chuwy** [comment]
Sorry @szareiangm, this wontfix. Json4s 3.2.11 is part of Spark and (therefore) whole our Scala stack. And all further Json4s versions are binary-incompatible with 3.2.11, which means if we'll include Iglu Client into any our application - it will fail with runtime exception. On the other hand, we're planning to migrate [to circe](https://github.com/snowplow/iglu-scala-client/issues/74) in a not very distant future (not ready yet). Closing this.
