### ISSUE TITLE
Bump Scalaz to 7.2.25

### ISSUE THREAD

**Issue by szareiangm** [snowplow/iglu-scala-client#91]
A bump until decision is made on #67

**Comment by chuwy** [comment]
Hey @szareiangm, sorry, but this is also wontfix for almost same reasons as #90. Minor versions of Scalaz are incompatible with each other, which means we'll have to bump Scalaz simultaneously in all our applications and libraries using Iglu Client. On the bright side, we're all agree on #67 that we'll migrate to cats in all our codebases (migration should be much safer).
