### ISSUE TITLE
Drop Scala 2.10

### ISSUE THREAD

**Issue by szareiangm** [snowplow/iglu-scala-client#93]
We agreed on this in #66

**Comment by chuwy** [comment]
Just a small neat (really sorry for bike-shedding): most our "infrastructure/bump" tickets have their "standard" easy-searchable titles, like https://github.com/snowplow/snowplow/issues/3285. This is in the case contributor needs help in implementing them and wants to search prior art.

**Comment by szareiangm** [comment]
Sorry about not following your conventions, still trying to learn. 🙌
